/**
 * server.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Entry point for the AI Interview Bot Node.js service.
 *
 * Serves:
 *   - /bot-test/*        → Interview bot routes (join meeting, call events)
 *   - /public/audio/*    → Static WAV audio files generated by Azure TTS
 *                          (Microsoft Graph recordResponse plays these URLs)
 * ─────────────────────────────────────────────────────────────────────────────
 */
const express = require("express");
const path    = require("path");
require("dotenv").config();
const botRoutes = require("./routes/botMessages");
const app = express();

// ── Middleware ────────────────────────────────────────────────────────────────
app.use(express.json());

// ── Static file server — TTS audio files ─────────────────────────────────────
// Serves files from nodejs/public/audio/ at /public/audio/<filename>
// Microsoft Graph's recordResponse requires a public HTTPS URL for audio prompts.
app.use(
    "/public/audio",
    express.static(path.join(__dirname, "public", "audio"), {
        // Cache audio for 1 hour — files are read-once by Graph during the call
        maxAge: "1h",
        setHeaders: (res) => {
            // Required MIME type for WAV audio files
            res.setHeader("Content-Type", "audio/wav");
        }
    })
);

// ── Bot API routes ────────────────────────────────────────────────────────────
app.use("/", botRoutes);

// ── Health check ─────────────────────────────────────────────────────────────
app.get("/health", (req, res) => {
    res.json({
        status:    "ok",
        service:   "AI Interview Bot",
        timestamp: new Date().toISOString()
    });
});
// ── Start server ──────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 4001;
app.listen(PORT, () => {

    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log(`  🤖 AI Interview Bot running on port ${PORT}`);
    console.log(`  📁 Audio served at /public/audio`);
    console.log(`  🩺 Health: http://localhost:${PORT}/health`);
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

});